version: '3.7'

services:
  mercure:
    image: dunglas/mercure
    container_name: mercure-container
    restart: unless-stopped
    ports:
            - '9191:80'
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: ${MERCURE_PUBLISHER_JWT_KEY}
      MERCURE_SUBSCRIBER_JWT_KEY: ${MERCURE_SUBSCRIBER_JWT_KEY}
      DEBUG: 1
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins https://localhost:8000

    command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    volumes:
      - mercure_data:/data
      - mercure_config:/config

  mariadb-service:
        image: 'mariadb:latest'
        container_name: mariadb-container
        restart: unless-stopped
        environment:
            MYSQL_PASSWORD: 'root'
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: app
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - '3306:3306'

volumes:
  mercure_data:
  mercure_config:
  db_data:
